name: Deploy to Vercel

on:
  push:
    branches:
      - main # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: vercel-deployment
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-project-name: ${{ secrets.PROJECT_NAME }}
    outputs:
      preview-url: ${{ secrets.PREVIEW_URL }}
